package v4l2

// These constants were mimicked from:
// /include/uapi/asm-generic/ioctl.h
const (
	CONST_IOC_NRBITS   = 8
	CONST_IOC_TYPEBITS = 8

	CONST_IOC_SIZEBITS = 14
	CONST_IOC_DIRBITS  = 2

	CONST_IOC_NRMASK   = ((1 << CONST_IOC_NRBITS)-1)
	CONST_IOC_TYPEMASK = ((1 << CONST_IOC_TYPEBITS)-1)
	CONST_IOC_SIZEMASK = ((1 << CONST_IOC_SIZEBITS)-1)
	CONST_IOC_DIRMASK  = ((1 << CONST_IOC_DIRBITS)-1)

	CONST_IOC_NONE  = 0
	CONST_IOC_WRITE = 1
	CONST_IOC_READ  = 2

	CONST_IOC_NRSHIFT   = 0
	CONST_IOC_TYPESHIFT = (CONST_IOC_NRSHIFT   + CONST_IOC_NRBITS)
	CONST_IOC_SIZESHIFT = (CONST_IOC_TYPESHIFT + CONST_IOC_TYPEBITS)
	CONST_IOC_DIRSHIFT  = (CONST_IOC_SIZESHIFT + CONST_IOC_SIZEBITS)
)

